name: jslinter

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/jslinter.yml"
      - ".eslintrc"
      - "src/**.js"
      - "index.js"

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16'

      - name: Install ESLint
        run: yarn add eslint

      - name: Run ESLint
        run: yarn run lint
